version: "3.8"

services:
  web:
    container_name: tasksapp
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: tasksdb
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    logging:
      driver: none


#LO que corregui para que funcionara el docker, fue cambiarle el nombre a mongo